### ISSUE TITLE
Minimal Valuable Product: As a user I want to connect my device with my user account

### ISSUE THREAD

**Issue by ozfox** [smartuni/teamagochi#13]
Requirements:

1. A user needs to be able to create an user account
2. A new device needs to register with the server
3. A user is able to connect a user account and a device in a secure manner

For this to be done each team needs to come up with required steps and problems to solve.

**Comment by AnnsAnns** [comment]
(I can't add you as a stakeholder for this issue for some reason @yasuaki-kumazaki)

**Comment by AnnsAnns** [comment]
Superseeded by #30
