### ISSUE TITLE
Evaluate Display functionality

### ISSUE THREAD

**Issue by moritzholzer** [smartuni/teamagochi#5]
which type of display (monochromatic or color/ touch or not)

How we want to draw the Pet

**Comment by AnnsAnns** [comment]
One potential library for that could be https://github.com/memononen/nanovg

**Comment by leandrolanzieri** [comment]
FYI: RIOT supports LVGL as a package https://lvgl.io/
Here is an example application https://github.com/RIOT-OS/RIOT/tree/master/tests/pkg/lvgl, and here another one but with touch support https://github.com/RIOT-OS/RIOT/tree/master/tests/pkg/lvgl_touch

**Comment by AnnsAnns** [comment]
These don't have a lot of pins, would need a driver though:
https://www.az-delivery.de/en/products/0-96zolldisplay
https://www.amazon.de/GeeekPi-Display-zweifarbiges-Raspberry-Arduino/dp/B0BB1T23LF

This one has a driver for riot and has colour but also consumes 500 trillion pins: https://doc.riot-os.org/group__drivers__ili9341.html

**Comment by AnnsAnns** [comment]
If we're going to use the microcontroller we currently have we should probably just go with one of the two non-driver boards. Both use simple I²C so it should be fine.

**Comment by moritzholzer** [comment]
- i got the following tft to work:
https://www.adafruit.com/product/1651
- pinout: 
https://learn.adafruit.com/adafruit-2-8-tft-touch-shield-v2/stmpe-resistive-pinout (and use an arduino pionout for reference)
- code is under the tftTest branch
when we dont use the touchscreen we need following pins:
- 3.3V
- Ground
- SCKL
- MOSI
- CS
- DC

in RIOT/drivers/ili9341/include/li9341_params.h the pins are changed to: 
#define ILI9341_PARAM_CS           GPIO_PIN(0, 27)
#define ILI9341_PARAM_DCX          GPIO_PIN(0, 26)
Which are ports 10 and 9 on the feather reference: https://learn.adafruit.com/introducing-the-adafruit-nrf52840-feather/pinouts

**Comment by AnnsAnns** [comment]
Amazing work! Holy heck

**Comment by AnnsAnns** [comment]
Done
